name: Docker Actions

on: [push, pull_request]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: meow
        uses: ./.github/actions/cat-facts
        id: cat
